import Head from "next/head";

export default function Contact() {
  return (
    <div className="mt-20 mb-40 font-Josefin">
      <Head>
        <title>Bark Trädgård</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="p-20 bg-green-100">
            <p className="text-xl mb-4">Hör av dig för en gratis offert eller med dina frågor</p>
            <p className="text-xl font-semibold">0732 31 44 55</p>
            <p className="text-xl font-semibold">carlmagnusbark@gmail.com</p>
        </div>
      </div>
  );
}
