import Head from "next/head";
import Image from "next/image";
import ServiceCard from "../components/services/ServiceCard";

const service = [
  {
    id: "1",
    company: "Planering och anläggning",
    offer: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It",
    image: "/images/shAsset 2@4x.png",
  },
  {
    id: "2",
    company: "Underhåll och skötsel",
    offer: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It",
    image: "/images/shAsset 4@4x.png",
  },
  {
    id: "3",
    company: "Beskärning och klippning",
    offer: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It",
    image: "/images/shAsset 1@4x.png",
  },
  {
    id: "4",
    company: "Trädgårdskonst",
    offer: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It",
    image: "/images/shAsset 3@4x.png",
  },
];


export default function Home() {
  return (
    <div className="font-Josefin">
      <Head>
        <title>Bark Trädgård</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-row ">
        <Image
          src="/images/IMG-3393.jpeg"
          alt="Picture of the author"
          width={3024}
          height={4032}
        />
        <Image
          src="/images/RitningVillaAston.jpg"
          alt="Picture of the author"
          width={3024}
          height={4032}
        />
      </div>
      <p className="absolute lg:top-1/2 top-1/4 left-1/2 transform -translate-x-1/2 -translate-y-1/2 lg:text-15xl text-10xl font-semi-bold text-white">BARK</p>
      <p className="absolute bg-green-100 p-2 lg:top-3/4 top-80 left-1/2 transform -translate-x-1/2 -translate-y-1/2 lg:text-2xl text-lg font-semi-bold text-black">Trädgårdsarbete för privatpersoner, företag och offentlig verksamhet</p>
      <div className="grid lg:grid-cols-2 gap-5 ml-10 mr-10 mt-10 mb-10">
          {service.map((campaign) => (
            <ServiceCard
              key={campaign.id}
              name={campaign.company}
              offer={campaign.offer}
              image={campaign.image}
            />
          ))}
        </div>
    </div>
  );
}
