import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col lg:flex-row ">
        <Image
          src="/images/IMG-3393.jpeg"
          alt="Picture of the author"
          // layout="fill"
          width={3024}
          height={4032}
        />
        <Image
          src="/images/RitningVillaAston.jpg"
          alt="Picture of the author"
          // layout="fill"
          width={3024}
          height={4032}
        />
      </div>
      <p className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 lg:text-15xl text-10xl font-semi-bold text-white">BARK</p>
    </div>
  );
}
